version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/open-jdk"
    
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo '...starting build...'
      - ls /usr/lib/
      - ls /usr/lib/jvm/
      #- ./gradlew build
      #- java -version
      #- which java
artifacts:
  files:
    - '**/*'