version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java"
    
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo '...starting build...'
      #- ./gradlew build
      - java -version
      - which java
artifacts:
  files:
    - '**/*'