version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo '...starting build...'
      - ./gradlew build
artifacts:
  files:
    - '**/*'